/*
 * Copyright 2026, TeamDev. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

@file:Suppress("ConstPropertyName")

package io.spine.gradle.publish

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.gradle.api.file.DuplicatesStrategy

/**
 * Configures a `ShadowJar` task for Spine SDK publishing.
 */
@Suppress("unused")
fun ShadowJar.setup() {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE  // Required for service-file merging.
    handleMergingServiceFiles()
    deduplicateEntries()
}

/**
 * Calls [ShadowJar.mergeServiceFiles] for the files we use in the Spine SDK.
 */
private fun ShadowJar.handleMergingServiceFiles() {
    ServiceFiles.all.forEach {
        append(it)
    }
    append(DescriptorSetReferenceFile.name)
}

/**
 * Installs a first-copy-wins exclusion predicate for all JAR entries except those
 * registered for merging by [handleMergingServiceFiles].
 *
 * Shadow's [org.gradle.api.file.DuplicatesStrategy.INCLUDE] must remain on the task so
 * that every copy of a merged file reaches its
 * [AppendingTransformer][com.github.jengelman.gradle.plugins.shadow.transformers.AppendingTransformer].
 * All other entries — `.class` files, settings JSONs, Kotlin module descriptors,
 * Maven metadata, etc. — are deduplicated here to suppress duplicate-entry warnings
 * and keep the fat JAR size minimal.
 */
private fun ShadowJar.deduplicateEntries() {
    val seenPaths = mutableSetOf<String>()
    doFirst { seenPaths.clear() }
    eachFile {
        val needsMerging = (path in ServiceFiles.all) || path.isDescriptorSetReference
        if (!needsMerging && !seenPaths.add(path)) {
            exclude()
        }
    }
}

/**
 * Returns `true` for file paths containing references to descriptor set files.
 */
private val String.isDescriptorSetReference: Boolean
    get() = this == DescriptorSetReferenceFile.name

/**
 * Provides the name of the file which contains the reference to the descriptor set file.
 */
internal object DescriptorSetReferenceFile {

    /**
     * This value must match `io.spine.code.proto.DescriptorSetReferenceFile.NAME`.
     */
    const val name = "desc.ref"
}

private object ServiceFiles {

    /**
     * The resource directory where service provider files are stored.
     */
    private const val servicesDir = "META-INF/services"

    /**
     * Providers of custom Protobuf options introduced by the libraries.
     */
    private const val optionProviders = "$servicesDir/io.spine.option.OptionsProvider"

    /**
     * Message validators provided by the libraries.
     */
    private const val messageValidators = "$servicesDir/io.spine.validation.MessageValidator"

    /**
     * Comparator providers provided by the libraries.
     */
    private const val comparatorProviders = "$servicesDir/io.spine.compare.ComparatorProvider"

    /**
     * KSP symbol processor provider.
     */
    private const val kspSymbolProcessorProviders =
        "$servicesDir/com.google.devtools.ksp.KspSymbolProcessorProvider"

    /**
     * Message routing setup classes generated by the Compiler for JVM.
     */
    private const val routeSetupPackage = "io.spine.server.route.setup"
    private const val routeSetupPrefix = "$servicesDir/$routeSetupPackage"
    private const val commandRoutingSetupClasses = "$routeSetupPrefix.CommandRoutingSetup"
    private const val eventRoutingSetupClasses = "$routeSetupPrefix.EventRoutingSetup"
    private const val stateRoutingSetupClasses = "$routeSetupPrefix.StateRoutingSetup"

    val all = setOf(
        optionProviders,
        messageValidators,
        comparatorProviders,
        kspSymbolProcessorProviders,
        commandRoutingSetupClasses,
        eventRoutingSetupClasses,
        stateRoutingSetupClasses
    )
}
