/*
 * Copyright 2026, TeamDev. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package io.spine.tools.core.jvm.gradle.plugins

import io.kotest.matchers.collections.shouldContainExactly
import io.kotest.matchers.shouldBe
import io.spine.tools.core.jvm.gradle.CoreJvmCompiler
import java.io.File
import javax.xml.parsers.DocumentBuilderFactory
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import org.w3c.dom.Element

/**
 * Guards the POM of the plugin marker, through which Gradle resolves
 * the CoreJvm Gradle Plugin by its [ID][CoreJvmPlugin.ID].
 *
 * `java-gradle-plugin` gives the marker a dependency on the coordinates of
 * its `pluginMaven` publication, which the build of this module replaces with
 * its own publication of the plugin. The build script patches the marker POM
 * so that it depends on the published plugin artifact only. This suite checks
 * the POM that the build generates.
 */
@DisplayName("The POM of the plugin marker should")
internal class PluginMarkerPomSpec {

    companion object {

        private const val PLUGIN_MARKER_POM_PROPERTY = "plugin.marker.pom"

        /**
         * The root element of the marker POM generated by the build.
         *
         * The path to the POM arrives through a system property set by
         * the `test` task in `gradle-plugin/build.gradle.kts`.
         */
        private val pom: Element by lazy {
            val path = checkNotNull(System.getProperty(PLUGIN_MARKER_POM_PROPERTY)) {
                "System property `$PLUGIN_MARKER_POM_PROPERTY` is not set."
            }
            DocumentBuilderFactory.newInstance()
                .apply { isNamespaceAware = true }
                .newDocumentBuilder()
                .parse(File(path))
                .documentElement
        }
    }

    @Test
    fun `keep the coordinates derived from the plugin ID`() {
        pom.childText("groupId") shouldBe CoreJvmPlugin.ID
        pom.childText("artifactId") shouldBe "${CoreJvmPlugin.ID}.gradle.plugin"
    }

    @Test
    fun `depend only on the plugin artifact, at runtime`() {
        val plugin = CoreJvmCompiler.gradlePlugin
        val expected = "${plugin.group}:${plugin.name}:${pom.childText("version")}:runtime"
        pom.dependencies().map { it.coordinates() } shouldContainExactly listOf(expected)
    }
}

/**
 * Returns the `<dependency>` elements of this POM, under any `<dependencies>` element.
 */
private fun Element.dependencies(): List<Element> =
    childElements("dependencies").flatMap { it.childElements("dependency") }

/**
 * Returns the coordinates of this `<dependency>` as `groupId:artifactId:version:scope`,
 * with `null` in place of an element the dependency lacks.
 */
private fun Element.coordinates(): String =
    listOf("groupId", "artifactId", "version", "scope")
        .joinToString(":") { childText(it).toString() }

/**
 * Returns the text of the only child element with the given [name],
 * or `null` if there is no such element, or more than one.
 */
private fun Element.childText(name: String): String? =
    childElements(name).singleOrNull()?.textContent?.trim()

/**
 * Returns the child elements of this element with the given local [name].
 */
private fun Element.childElements(name: String): List<Element> =
    (0 until childNodes.length)
        .map { childNodes.item(it) }
        .filterIsInstance<Element>()
        .filter { it.localName == name }
