name: Build under Windows

on: pull_request

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

      - name: SetPageFile
        run: |
          Invoke-WebRequest http://www.paraglidernc.com/Files/SetPageFile1008.cab -OutFile SetPageFile1008.cab
          expand.exe SetPageFile1008.cab -F:* C:\
          C:\files\SetPageFile.exe /f D:\pagefile.sys /m 8192

      - name: Build project and run tests
        shell: cmd
        # For the reason on `--no-daemon` see https://github.com/actions/cache/issues/454
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          gradlew.bat build --stacktrace --no-daemon

      # See: https://github.com/marketplace/actions/junit-report-action
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.7.6
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          require_tests: true # will fail workflow if test reports not found
