name: Build under Ubuntu

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: zulu
          cache: gradle

      - name: Pull config
        run: git submodule update --init --recursive

      - name: Build project and run tests
        shell: bash
        run: ./gradlew build --stacktrace

      - name: Upload code coverage report
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true

      - name: Pack build artifacts for upload
        shell: bash
        run: tar -czvf mc-java-ci-build-results.tar.gz ./*

      - name: Upload build results
        uses: actions/upload-artifact@v2
        with:
          name: mc-java-ci-build-results
          path: mc-java-ci-build-results.tar.gz
          retention-days: 1
