name: Integration Tests

on:
  workflow_run:
    workflows: [ "Build under Ubuntu" ]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Print status message
        shell: bash
        run: echo "Downloading CI build results..."

      - name: Download CI build results
        # This custom action allows downloading the `actions/upload-artifact@v2` results.
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-on-ubuntu.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: mc-java-ci-build-results
          path: ./

      - name: Unpack the downloaded file
        shell: bash
        run: tar -xzvf mc-java-ci-build-results.tar.gz

      - name: Run tests
        shell: bash
        run: |
          pwd
          ls
          cd tests
          ./gradlew build --stacktrace
