name: Test build performance

on: pull_request

jobs:
  build:
    name: Test build performance
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Measure build performance
        shell: bash
        run: ./gradlew checkPerformance --stacktrace
